In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [14]:
print(a.reshape(-1,1))
b = np.linspace(1,10,50).reshape(10,5)
c = b[0:3,:]
c

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


array([[1.        , 1.18367347, 1.36734694, 1.55102041, 1.73469388],
       [1.91836735, 2.10204082, 2.28571429, 2.46938776, 2.65306122],
       [2.83673469, 3.02040816, 3.20408163, 3.3877551 , 3.57142857]])